### ISSUE TITLE
 RuntimeWarning: invalid value encountered in true_divide   totp /= totw

### ISSUE THREAD

**Issue by xrstack** [EnricoAhlers/agi2nerf#3]
z:\instant-ngp\scripts\agi2nerf.py:41: RuntimeWarning: invalid value encountered in true_divide
  totp /= totw
[nan nan nan]

Results in a 1kb output file with only one pose in it

**Comment by EnricoAhlers** [comment]
Probably too late but maybe it'll help someone else. I pushed a fix that should solve it.

**Comment by aburakkoc** [comment]
can you elaborate more on how to fix this issue? i am having the same problem

**Comment by filippide** [comment]
Hi, I'm sorry to tell you but the problem still exist. I tryed metashape 1.8
 RuntimeWarning: invalid value encountered in divide
  totp /= totw
[nan nan nan]
[example.txt](https://github.com/EnricoAhlers/agi2nerf/files/11045333/example.txt)

[transforms.txt](https://github.com/EnricoAhlers/agi2nerf/files/11045336/transforms.txt)
